import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by nextjs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex w-screen">
          <span className="text-4xl font-bold text-blue-600">SuperApp</span>
      </div>
    </div>
  );
}
